import Head from "next/head";
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <div className="relative bg-blue-200 rounded-xl p-6 shadow-md w-80">

          <svg

            viewBox="0 0 200  200"

          >


            <path

              d="M10,110 A120,120 -45 0,1 110 10 A120,120 -45 0,1 10,110"

              stroke="black"

              stroke-width="2"

              fill="none"

              id="motionPath" />
            <image
              className=""
              href="https://upload.wikimedia.org/wikipedia/pt/thumb/8/8a/Better_Call_Saul_logo.svg/2560px-Better_Call_Saul_logo.svg.png"

              width="250"

              height="200">

            </image>




            <path

              d="M10,110 A110,120 -40 0,1 110 10 A120,120 -45 0,1 10,110"

              stroke="black"

              stroke-width="2"

              fill="none"

              id="motionPaths" />
            <circle cx="10" cy="110" r="3" fill="lightgrey" />
            <circle cx="110" cy="10" r="3" fill="lightgrey" />


            <image
              className=" z-50"
              href="https://upload.wikimedia.org/wikipedia/pt/thumb/8/8a/Better_Call_Saul_logo.svg/2560px-Better_Call_Saul_logo.svg.png"

              width="100"

              height="20">
              <animateMotion

                dur="3s"

                repeatCount="indefinite"

                keyPoints="0;0.5;1"

                keyTimes="0;0.15;1"

                calcMode="linear">
                <mpath href="#motionPath" />
              </animateMotion>
            </image>
          </svg>

        </div>
      </main>
    </>
  );
}
